sudo: false
language: node_js
cache:
  - bundler
node_js:
  - "4"
  - "0.12"
before_install:
  - rvm use 2.2.2 --install --fuzzy
  - bundle install
before_script:
  - npm install -g grunt-cli
matrix:
  fast_finish: true
