sudo: required
env:
  global:
    # firebase deploy key
    secure: jGUozjHY6+d+pYYCmbVUfipgOdDg/lu3tLhFz7Cf+3dfopr6EEwCuttmphraQsnxoIhjDso4oLS59KknAIbqBLOwoHwV2wZqMlGXEmJsz+tjwVKNoaVa6DapdepnTSmsHbeE+C30SyJzV7WO4SYFsmVJJF4vdNj3Xt0e6p0K3/zuADX8kJXBDkgmO9K3ITzkO4zFhyQxUB2qneV+IqOdunyrKV3G8qGlxi8kZyJPG4+aeQXSlP9VCbgjM4fdLJmCkMOaBrvBrTTNHL9aFzhTlFQCXRaps1tVsWEVyRu66nOBvxGnFtUkL13nIk28DUHGYQb0mtm6ksNgz8K/RH2dIuUwJ7uWjRp7k+k3N/WgyVygA8fMmkAU+QuMKDwht38D7dOZAZ3veIqafUG+kMmOlK35WV/IZvE1xKB57pTHlww2kTSG13dFIYOFOidiBfSRupMOCcuDWpuBistxE2MasFU9vooUwJ65cUxhSA86qlZLwHwjdBIjfk0AfTkaOj1rV54ub/r/wKkRMwy/st/jc/9z7os4w5FwioDqL8vS6jRUYdzb7DS973ZaAkE4OZWs35JInJic7z/i56feMhtqqUeyktXHVsxlfdeLpiXZYMInyZOnzIOYnMnBx3kShy9s7iV0n+P5NxL854kTI4eXTvRw3AFLqyYRnLBtV172DM8=

install:
- wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.34/hugo_0.34_Linux-64bit.deb
- sudo dpkg -i /tmp/hugo.deb

script:
- hugo
