sudo: required
install:
- wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.34/hugo_0.34_Linux-64bit.deb
- sudo dpkg -i /tmp/hugo.deb

before_deploy: hugo

deploy:
  provider: firebase
  token:
    secure: "f0VtfBnyMewgcY/Wh9umIbHVSLdgGxlcDQMhoVIF5PHcNdre1PjdDl+cmCac+tffhFls9reN9Zw+jjm/IGFsz6o2Wzep5ItqYBttvVcMiqIC5dtbEjsZVyS7lt1ZYuDKvxc+wiNAm7wr35vyirpYlWKUj8jyknUQat78J+XhxaJ7vEdWfmVGLOoQQ/ee9tO9C3vrlb9NNEJOggaD5euwmFeycV+YtxAatDeAagc/Ih8fF2AmEy9nMM9BK8InCJG1rUwKVxVuAs/SvRI/9nSRR8CFkXA4Re+pNvS4Fqx/YRZ0QYLxw+GAHOjSCIqQa7108vdtEjouQTzTG08x59QjDeLDzeFW25bVmN2mlVVx6ZkBeRlEGswv7JBayAsmvv1CVmzEAzGb9fIrh/onDcYOzDUwcTvrQnZHGnRkl0iqn/jw7WKgFlH3Cs44vSBU+U3kDJTkZZzuyH16I8uXb7I8YhMHWwq5+h8gbsohxfaUtlqrIuL6iB2MPEhJyCogh4QqUgYO4/kDtySxhCy/SCx1b9WgcjlIFCIEGcP5zeAebsBJTyefpoQYhCAyD/KAr59kwN8QI6a3BfgDPPhgWHQGtHbfbdPZHDoFsbXGdo29lB3JVmE6f2z07PnMlfgj0PaQZ/CDuovRYmzCgnmFcPyg46lRdX0ftn8j+LeH34AA+2c="
