#
# More configuration examples at:
# http://jekyllrb.com/docs/configuration/
#

#
# Jekyll basic configurations
#

source:         _app
destination:    _site
timezone:       America/New_York
permalink:      /:categories/:title/
markdown:       kramdown
highlighter:    rouge
include:        ["_pages"]
exclude:        ["_pages/themes"]

#
# Jekyll serve settings
#

port:           4321

#
# Jekyll build settings
#

future:         false

#
# Additional Markdown settings
#

kramdown:
  input:                     GFM
  auto_ids:                  true
  footnote_nr:               1
  entity_output:             as_char
  toc_levels:                1..6
  smart_quotes:              lsquo,rsquo,ldquo,rdquo
  enable_coderay:            false
  hard_wrap:                 false
  syntax_highlighter:        rouge
  transliterated_header_ids: true
  footnote_backlink:         "&#8617;&#xfe0e;"

#
# Jekyll plugins
#

gems:
  - jekyll-last-modified-at

#
# Almace Scaffolding settings
#

# Development mode
dev:            false

# Site name
name:           noqcks

# Site description, will appear in the document meta and Atom feed subtitle
description: DevOps engineer from Toronto, CANADA

# Base URL, this is useful when I need to build site in a subdirectory (like GitHub Pages for Projects), it provides a specific URL prefix, for example, if the production site URL is http://sparanoid.com/lab/version/, set `base` to `/lab/version/24`, without trailing slash.
# Default:      ""
base:           ""

# CSS path used in templates
# Default:      /assets
assets:         /assets

# Define your main feed URL, this will be only used in your templates
# Default:      /feed.xml
feed:           /feed.xml

# PubSubHubbub Hub
# Default:      https://pubsubhubbub.appspot.com/
pshh:           https://pubsubhubbub.appspot.com/

# Used in atom feed, sitemap, Twitter Cards, and etc. I should use absolute full URLs for these fields
url:            https://noqcks.io

# Media assets URL used in posts, without trailing slash. ie. `<img src="{{ site.file }}/image.png">`. In the most cases this URL should be powered by a CDN provider
file:           /assets/img

# Download files URL used in posts, ie. href="{{ site.download }}/package.zip", this should also be a CDN link just like `site.url`. There's no differences in `site.url` and `site.download`, I just use one CDN for post images and another for large download files. That's it. Remove or ignore this if you don't need it
download:       https://noqcks.io/downloads

# Google Analytics tracking code
google_analytics:
  enabled:      true
  id:           UA-74722275-1
  url:          //www.google-analytics.com/analytics.js

# Site Twitter account handle
twitter:        noqcks

# Force UTF-8 encoding, enable this will simply add <meta charset="utf-8"> to the head of your pages
# Default:      false
force_utf_8:    false

# Enable this settings to make your feed Daring Fireball-like link blog
# (This basically change your <link> value to external link you defined in your posts)
# Default:      false
link_blog:      false

# Change the value to true to use post excerpt for RSS feeds
# Default:      false
rss_excerpt:    false

# Show generator credits
# Default:      true
credits:        false

# Items in robots.txt
# For example:
# robots:
#   - "User-agent: *"
#   - "Disallow: /ajax/"
#   - "Disallow: /@async"
#   - "Disallow: /log/"
# Default:      "User-agent: *"
robots:
  - "User-agent: *"
  - "Disallow: /lab/version/"
