baseurl = "/"
languageCode = "en-us"
title = "noqcks"
googleAnalytics = "UA-74722275-1"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
staticDir = ["static"]
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License"
canonifyURLs = true

[permalinks]
    notes = "/notes/:year/:month/:day/:slug/"
    work = "/work/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Work"
    url = "/work/"
    weight = 2
[[menu.main]]
    name = "Notes"
    url = "/notes/"
    weight = 2
[[menu.main]]
    name = "OSS-Contrib"
    url = "/oss-contrib/"
    weight = 2

[params]
    description = "Benji Visser"
    footer = "[home](/) | [tags](/tags)"

[outputs]
home = [ "RSS", "HTML"]

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feed"
